---
version: '2.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /Users/c.panzi/Projects/inshort/docker/mongo:/data/db
  inshort:
    image: kajyr/inshort
    restart: always
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/admin
      API_KEY: 1239u1
    ports:
      - 7000:7000
