---
version: '2.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 7001:27017
    volumes:
      - /Users/c.panzi/Projects/inshort/docker/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 7002:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
